#pragma once

#include "adif.h"

/* adif.h.in
 * This file provides the structure definitions and function prototypes
 * for handling ADIF (Amateur Data Interchange Format) files.
 */

 #include <stdint.h>
 #include <map>
 #include <string>

 namespace adif {
	//! Map linking field enumeration values to their metadata
	static std::map<field_t, field_info_t> adif::FIELD_INFO_MAP = {
	
{ ADDRESS, { "ADDRESS", "MultilineString" , ""} },
{ ADDRESS_INTL, { "ADDRESS_INTL", "IntlMultilineString" , ""} },
{ ADIF_VER, { "ADIF_VER", "String" , ""} },
{ AGE, { "AGE", "Number" , ""} },
{ ALTITUDE, { "ALTITUDE", "Number" , ""} },
{ ANT_AZ, { "ANT_AZ", "Number" , ""} },
{ ANT_EL, { "ANT_EL", "Number" , ""} },
{ ANT_PATH, { "ANT_PATH", "Enumeration" , "Ant_Path"} },
{ APP_LOTW_LASTQSL, { "APP_LOTW_LASTQSL", "String" , ""} },
{ APP_LOTW_NUMREC, { "APP_LOTW_NUMREC", "String" , ""} },
{ APP_QRZLOG_LOGID, { "APP_QRZLOG_LOGID", "String" , ""} },
{ APP_QRZLOG_QSLDATE, { "APP_QRZLOG_QSLDATE", "String" , ""} },
{ APP_QRZLOG_STATUS, { "APP_QRZLOG_STATUS", "String" , ""} },
{ APP_ZZA_CQ, { "APP_ZZA_CQ", "String" , ""} },
{ APP_ZZA_ECARD, { "APP_ZZA_ECARD", "String" , ""} },
{ APP_ZZA_EQSL_MSG, { "APP_ZZA_EQSL_MSG", "String" , ""} },
{ APP_ZZA_ERROR, { "APP_ZZA_ERROR", "String" , ""} },
{ APP_ZZA_MY_CONT, { "APP_ZZA_MY_CONT", "String" , ""} },
{ APP_ZZA_MY_WAB, { "APP_ZZA_MY_WAB", "String" , ""} },
{ APP_ZZA_NUMRECORDS, { "APP_ZZA_NUMRECORDS", "String" , ""} },
{ APP_ZZA_OP, { "APP_ZZA_OP", "String" , ""} },
{ APP_ZZA_OPERATOR, { "APP_ZZA_OPERATOR", "String" , ""} },
{ APP_ZZA_OP_DESCR, { "APP_ZZA_OP_DESCR", "String" , ""} },
{ APP_ZZA_PFX, { "APP_ZZA_PFX", "String" , ""} },
{ APP_ZZA_QSL_ROUTE, { "APP_ZZA_QSL_ROUTE", "String" , ""} },
{ APP_ZZA_QTH, { "APP_ZZA_QTH", "String" , ""} },
{ APP_ZZA_QTH_DESCR, { "APP_ZZA_QTH_DESCR", "String" , ""} },
{ ARRL_SECT, { "ARRL_SECT", "Enumeration" , "ARRL_Section"} },
{ AWARD_GRANTED, { "AWARD_GRANTED", "SponsoredAwardList" , ""} },
{ AWARD_SUBMITTED, { "AWARD_SUBMITTED", "SponsoredAwardList" , ""} },
{ A_INDEX, { "A_INDEX", "Number" , ""} },
{ BAND, { "BAND", "Enumeration" , "Band"} },
{ BAND_RX, { "BAND_RX", "Enumeration" , "Band"} },
{ CALL, { "CALL", "String" , ""} },
{ CHECK, { "CHECK", "String" , ""} },
{ CLASS, { "CLASS", "String" , ""} },
{ CLUBLOG_QSO_UPLOAD_DATE, { "CLUBLOG_QSO_UPLOAD_DATE", "Date" , ""} },
{ CLUBLOG_QSO_UPLOAD_STATUS, { "CLUBLOG_QSO_UPLOAD_STATUS", "Enumeration" , "QSO_Upload_Status"} },
{ CNTY, { "CNTY", "Enumeration" , "Secondary_Administrative_Subdivision[DXCC]"} },
{ CNTY_ALT, { "CNTY_ALT", "SecondaryAdministrativeSubdivisionListAlt" , ""} },
{ COMMENT, { "COMMENT", "String" , ""} },
{ COMMENT_INTL, { "COMMENT_INTL", "IntlString" , ""} },
{ CONT, { "CONT", "Enumeration" , "Continent"} },
{ CONTACTED_OP, { "CONTACTED_OP", "String" , ""} },
{ CONTEST_ID, { "CONTEST_ID", "String" , ""} },
{ COUNTRY, { "COUNTRY", "String" , ""} },
{ COUNTRY_INTL, { "COUNTRY_INTL", "IntlString" , ""} },
{ CQZ, { "CQZ", "PositiveInteger" , ""} },
{ CREATED_TIMESTAMP, { "CREATED_TIMESTAMP", "String" , ""} },
{ CREDIT_GRANTED, { "CREDIT_GRANTED", "CreditList,AwardList" , ""} },
{ CREDIT_SUBMITTED, { "CREDIT_SUBMITTED", "CreditList,AwardList" , ""} },
{ DARC_DOK, { "DARC_DOK", "Enumeration" , ""} },
{ DCL_QSLRDATE, { "DCL_QSLRDATE", "Date" , ""} },
{ DCL_QSLSDATE, { "DCL_QSLSDATE", "Date" , ""} },
{ DCL_QSL_RCVD, { "DCL_QSL_RCVD", "Enumeration" , "QSL_Rcvd"} },
{ DCL_QSL_SENT, { "DCL_QSL_SENT", "Enumeration" , "QSL_Sent"} },
{ DISTANCE, { "DISTANCE", "Number" , ""} },
{ DXCC, { "DXCC", "Enumeration" , "DXCC_Entity_Code"} },
{ EMAIL, { "EMAIL", "String" , ""} },
{ EQSL_AG, { "EQSL_AG", "Enumeration" , "EQSL_AG"} },
{ EQSL_QSLRDATE, { "EQSL_QSLRDATE", "Date" , ""} },
{ EQSL_QSLSDATE, { "EQSL_QSLSDATE", "Date" , ""} },
{ EQSL_QSL_RCVD, { "EQSL_QSL_RCVD", "Enumeration" , "QSL_Rcvd"} },
{ EQSL_QSL_SENT, { "EQSL_QSL_SENT", "Enumeration" , "QSL_Sent"} },
{ EQ_CALL, { "EQ_CALL", "String" , ""} },
{ FISTS, { "FISTS", "PositiveInteger" , ""} },
{ FISTS_CC, { "FISTS_CC", "PositiveInteger" , ""} },
{ FORCE_INIT, { "FORCE_INIT", "Boolean" , ""} },
{ FREQ, { "FREQ", "Number" , ""} },
{ FREQ_RX, { "FREQ_RX", "Number" , ""} },
{ GRIDSQUARE, { "GRIDSQUARE", "GridSquare" , ""} },
{ GRIDSQUARE_EXT, { "GRIDSQUARE_EXT", "GridSquareExt" , ""} },
{ GUEST_OP, { "GUEST_OP", "String" , ""} },
{ HAMLOGEU_QSO_UPLOAD_DATE, { "HAMLOGEU_QSO_UPLOAD_DATE", "Date" , ""} },
{ HAMLOGEU_QSO_UPLOAD_STATUS, { "HAMLOGEU_QSO_UPLOAD_STATUS", "Enumeration" , "QSO_Upload_Status"} },
{ HAMQTH_QSO_UPLOAD_DATE, { "HAMQTH_QSO_UPLOAD_DATE", "Date" , ""} },
{ HAMQTH_QSO_UPLOAD_STATUS, { "HAMQTH_QSO_UPLOAD_STATUS", "Enumeration" , "QSO_Upload_Status"} },
{ HRDLOG_QSO_UPLOAD_DATE, { "HRDLOG_QSO_UPLOAD_DATE", "Date" , ""} },
{ HRDLOG_QSO_UPLOAD_STATUS, { "HRDLOG_QSO_UPLOAD_STATUS", "Enumeration" , "QSO_Upload_Status"} },
{ IOTA, { "IOTA", "IOTARefNo" , ""} },
{ IOTA_ISLAND_ID, { "IOTA_ISLAND_ID", "PositiveInteger" , ""} },
{ ITUZ, { "ITUZ", "PositiveInteger" , ""} },
{ K_INDEX, { "K_INDEX", "Integer" , ""} },
{ LAT, { "LAT", "Location" , ""} },
{ LON, { "LON", "Location" , ""} },
{ LOTW_QSLRDATE, { "LOTW_QSLRDATE", "Date" , ""} },
{ LOTW_QSLSDATE, { "LOTW_QSLSDATE", "Date" , ""} },
{ LOTW_QSL_RCVD, { "LOTW_QSL_RCVD", "Enumeration" , "QSL_Rcvd"} },
{ LOTW_QSL_SENT, { "LOTW_QSL_SENT", "Enumeration" , "QSL_Sent"} },
{ MAX_BURSTS, { "MAX_BURSTS", "Number" , ""} },
{ MODE, { "MODE", "Enumeration" , "Mode"} },
{ MORSE_KEY_INFO, { "MORSE_KEY_INFO", "String" , ""} },
{ MORSE_KEY_TYPE, { "MORSE_KEY_TYPE", "Enumeration" , "Morse_Key_Type"} },
{ MS_SHOWER, { "MS_SHOWER", "String" , ""} },
{ MY_ALTITUDE, { "MY_ALTITUDE", "Number" , ""} },
{ MY_ANTENNA, { "MY_ANTENNA", "String" , ""} },
{ MY_ANTENNA_INTL, { "MY_ANTENNA_INTL", "IntlString" , ""} },
{ MY_ARRL_SECT, { "MY_ARRL_SECT", "Enumeration" , "ARRL_Section"} },
{ MY_CITY, { "MY_CITY", "String" , ""} },
{ MY_CITY_INTL, { "MY_CITY_INTL", "IntlString" , ""} },
{ MY_CNTY, { "MY_CNTY", "Enumeration" , "Secondary_Administrative_Subdivision[MY_DXCC]"} },
{ MY_CNTY_ALT, { "MY_CNTY_ALT", "SecondaryAdministrativeSubdivisionListAlt" , ""} },
{ MY_COUNTRY, { "MY_COUNTRY", "String" , ""} },
{ MY_COUNTRY_INTL, { "MY_COUNTRY_INTL", "IntlString" , ""} },
{ MY_CQ_ZONE, { "MY_CQ_ZONE", "PositiveInteger" , ""} },
{ MY_DARC_DOK, { "MY_DARC_DOK", "Enumeration" , ""} },
{ MY_DXCC, { "MY_DXCC", "Enumeration" , "DXCC_Entity_Code"} },
{ MY_FISTS, { "MY_FISTS", "PositiveInteger" , ""} },
{ MY_GRIDSQUARE, { "MY_GRIDSQUARE", "GridSquare" , ""} },
{ MY_GRIDSQUARE_EXT, { "MY_GRIDSQUARE_EXT", "GridSquareExt" , ""} },
{ MY_IOTA, { "MY_IOTA", "IOTARefNo" , ""} },
{ MY_IOTA_ISLAND_ID, { "MY_IOTA_ISLAND_ID", "PositiveInteger" , ""} },
{ MY_ITU_ZONE, { "MY_ITU_ZONE", "PositiveInteger" , ""} },
{ MY_LAT, { "MY_LAT", "Location" , ""} },
{ MY_LON, { "MY_LON", "Location" , ""} },
{ MY_MORSE_KEY_INFO, { "MY_MORSE_KEY_INFO", "String" , ""} },
{ MY_MORSE_KEY_TYPE, { "MY_MORSE_KEY_TYPE", "Enumeration" , "Morse_Key_Type"} },
{ MY_NAME, { "MY_NAME", "String" , ""} },
{ MY_NAME_INTL, { "MY_NAME_INTL", "IntlString" , ""} },
{ MY_POSTAL_CODE, { "MY_POSTAL_CODE", "String" , ""} },
{ MY_POSTAL_CODE_INTL, { "MY_POSTAL_CODE_INTL", "IntlString" , ""} },
{ MY_POTA_REF, { "MY_POTA_REF", "POTARefList" , ""} },
{ MY_RIG, { "MY_RIG", "String" , ""} },
{ MY_RIG_INTL, { "MY_RIG_INTL", "IntlString" , ""} },
{ MY_SIG, { "MY_SIG", "String" , ""} },
{ MY_SIG_INFO, { "MY_SIG_INFO", "String" , ""} },
{ MY_SIG_INFO_INTL, { "MY_SIG_INFO_INTL", "IntlString" , ""} },
{ MY_SIG_INTL, { "MY_SIG_INTL", "IntlString" , ""} },
{ MY_SOTA_REF, { "MY_SOTA_REF", "SOTARef" , ""} },
{ MY_STATE, { "MY_STATE", "Enumeration" , "Primary_Administrative_Subdivision[MY_DXCC]"} },
{ MY_STREET, { "MY_STREET", "String" , ""} },
{ MY_STREET_INTL, { "MY_STREET_INTL", "IntlString" , ""} },
{ MY_USACA_COUNTIES, { "MY_USACA_COUNTIES", "SecondarySubdivisionList" , ""} },
{ MY_VUCC_GRIDS, { "MY_VUCC_GRIDS", "GridSquareList" , ""} },
{ MY_WWFF_REF, { "MY_WWFF_REF", "WWFFRef" , ""} },
{ NAME, { "NAME", "String" , ""} },
{ NAME_INTL, { "NAME_INTL", "IntlString" , ""} },
{ NOTES, { "NOTES", "MultilineString" , ""} },
{ NOTES_INTL, { "NOTES_INTL", "IntlMultilineString" , ""} },
{ NR_BURSTS, { "NR_BURSTS", "Integer" , ""} },
{ NR_PINGS, { "NR_PINGS", "Integer" , ""} },
{ OPERATOR, { "OPERATOR", "String" , ""} },
{ OWNER_CALLSIGN, { "OWNER_CALLSIGN", "String" , ""} },
{ PFX, { "PFX", "String" , ""} },
{ POTA_REF, { "POTA_REF", "POTARefList" , ""} },
{ PRECEDENCE, { "PRECEDENCE", "String" , ""} },
{ PROGRAMID, { "PROGRAMID", "String" , ""} },
{ PROGRAMVERSION, { "PROGRAMVERSION", "String" , ""} },
{ PROP_MODE, { "PROP_MODE", "Enumeration" , "Propagation_Mode"} },
{ PUBLIC_KEY, { "PUBLIC_KEY", "String" , ""} },
{ QRZCOM_QSO_DOWNLOAD_DATE, { "QRZCOM_QSO_DOWNLOAD_DATE", "Date" , ""} },
{ QRZCOM_QSO_DOWNLOAD_STATUS, { "QRZCOM_QSO_DOWNLOAD_STATUS", "Enumeration" , "QSO_Download_Status"} },
{ QRZCOM_QSO_UPLOAD_DATE, { "QRZCOM_QSO_UPLOAD_DATE", "Date" , ""} },
{ QRZCOM_QSO_UPLOAD_STATUS, { "QRZCOM_QSO_UPLOAD_STATUS", "Enumeration" , "QSO_Upload_Status"} },
{ QSLMSG, { "QSLMSG", "MultilineString" , ""} },
{ QSLMSG_INTL, { "QSLMSG_INTL", "IntlMultilineString" , ""} },
{ QSLMSG_RCVD, { "QSLMSG_RCVD", "MultilineString" , ""} },
{ QSLRDATE, { "QSLRDATE", "Date" , ""} },
{ QSLSDATE, { "QSLSDATE", "Date" , ""} },
{ QSL_RCVD, { "QSL_RCVD", "Enumeration" , "QSL_Rcvd"} },
{ QSL_RCVD_VIA, { "QSL_RCVD_VIA", "Enumeration" , "QSL_Via"} },
{ QSL_SENT, { "QSL_SENT", "Enumeration" , "QSL_Sent"} },
{ QSL_SENT_VIA, { "QSL_SENT_VIA", "Enumeration" , "QSL_Via"} },
{ QSL_VIA, { "QSL_VIA", "String" , ""} },
{ QSO_COMPLETE, { "QSO_COMPLETE", "Enumeration" , "QSO_Complete"} },
{ QSO_DATE, { "QSO_DATE", "Date" , ""} },
{ QSO_DATE_OFF, { "QSO_DATE_OFF", "Date" , ""} },
{ QSO_RANDOM, { "QSO_RANDOM", "Boolean" , ""} },
{ QTH, { "QTH", "String" , ""} },
{ QTH_INTL, { "QTH_INTL", "IntlString" , ""} },
{ REGION, { "REGION", "Enumeration" , "Region"} },
{ RIG, { "RIG", "MultilineString" , ""} },
{ RIG_INTL, { "RIG_INTL", "IntlMultilineString" , ""} },
{ RST_RCVD, { "RST_RCVD", "String" , ""} },
{ RST_SENT, { "RST_SENT", "String" , ""} },
{ RX_PWR, { "RX_PWR", "Number" , ""} },
{ SAT_MODE, { "SAT_MODE", "String" , ""} },
{ SAT_NAME, { "SAT_NAME", "String" , ""} },
{ SFI, { "SFI", "Integer" , ""} },
{ SIG, { "SIG", "String" , ""} },
{ SIG_INFO, { "SIG_INFO", "String" , ""} },
{ SIG_INFO_INTL, { "SIG_INFO_INTL", "IntlString" , ""} },
{ SIG_INTL, { "SIG_INTL", "IntlString" , ""} },
{ SILENT_KEY, { "SILENT_KEY", "Boolean" , ""} },
{ SKCC, { "SKCC", "String" , ""} },
{ SOTA_REF, { "SOTA_REF", "SOTARef" , ""} },
{ SRX, { "SRX", "Integer" , ""} },
{ SRX_STRING, { "SRX_STRING", "String" , ""} },
{ STATE, { "STATE", "Enumeration" , "Primary_Administrative_Subdivision[DXCC]"} },
{ STATION_CALLSIGN, { "STATION_CALLSIGN", "String" , ""} },
{ STX, { "STX", "Integer" , ""} },
{ STX_STRING, { "STX_STRING", "String" , ""} },
{ SUBMODE, { "SUBMODE", "String" , ""} },
{ SWL, { "SWL", "Boolean" , ""} },
{ TEN_TEN, { "TEN_TEN", "PositiveInteger" , ""} },
{ TIME_OFF, { "TIME_OFF", "Time" , ""} },
{ TIME_ON, { "TIME_ON", "Time" , ""} },
{ TX_PWR, { "TX_PWR", "Number" , ""} },
{ UKSMG, { "UKSMG", "PositiveInteger" , ""} },
{ USACA_COUNTIES, { "USACA_COUNTIES", "SecondarySubdivisionList" , ""} },
{ USERDEFn, { "USERDEFn", "String" , ""} },
{ VE_PROV, { "VE_PROV", "String" , ""} },
{ VUCC_GRIDS, { "VUCC_GRIDS", "GridSquareList" , ""} },
{ WEB, { "WEB", "String" , ""} },
{ WWFF_REF, { "WWFF_REF", "WWFFRef" , ""} },

	{ FIELD_MAX, {"", "", ""} }
	};

	//! Map linking field names to their enumeration values
	static std::map<std::string, field_t> adif::FIELD_NAME_MAP = {
	
    { "ADDRESS", ADDRESS }, 
    { "ADDRESS_INTL", ADDRESS_INTL }, 
    { "ADIF_VER", ADIF_VER }, 
    { "AGE", AGE }, 
    { "ALTITUDE", ALTITUDE }, 
    { "ANT_AZ", ANT_AZ }, 
    { "ANT_EL", ANT_EL }, 
    { "ANT_PATH", ANT_PATH }, 
    { "APP_LOTW_LASTQSL", APP_LOTW_LASTQSL }, 
    { "APP_LOTW_NUMREC", APP_LOTW_NUMREC }, 
    { "APP_QRZLOG_LOGID", APP_QRZLOG_LOGID }, 
    { "APP_QRZLOG_QSLDATE", APP_QRZLOG_QSLDATE }, 
    { "APP_QRZLOG_STATUS", APP_QRZLOG_STATUS }, 
    { "APP_ZZA_CQ", APP_ZZA_CQ }, 
    { "APP_ZZA_ECARD", APP_ZZA_ECARD }, 
    { "APP_ZZA_EQSL_MSG", APP_ZZA_EQSL_MSG }, 
    { "APP_ZZA_ERROR", APP_ZZA_ERROR }, 
    { "APP_ZZA_MY_CONT", APP_ZZA_MY_CONT }, 
    { "APP_ZZA_MY_WAB", APP_ZZA_MY_WAB }, 
    { "APP_ZZA_NUMRECORDS", APP_ZZA_NUMRECORDS }, 
    { "APP_ZZA_OP", APP_ZZA_OP }, 
    { "APP_ZZA_OPERATOR", APP_ZZA_OPERATOR }, 
    { "APP_ZZA_OP_DESCR", APP_ZZA_OP_DESCR }, 
    { "APP_ZZA_PFX", APP_ZZA_PFX }, 
    { "APP_ZZA_QSL_ROUTE", APP_ZZA_QSL_ROUTE }, 
    { "APP_ZZA_QTH", APP_ZZA_QTH }, 
    { "APP_ZZA_QTH_DESCR", APP_ZZA_QTH_DESCR }, 
    { "ARRL_SECT", ARRL_SECT }, 
    { "AWARD_GRANTED", AWARD_GRANTED }, 
    { "AWARD_SUBMITTED", AWARD_SUBMITTED }, 
    { "A_INDEX", A_INDEX }, 
    { "BAND", BAND }, 
    { "BAND_RX", BAND_RX }, 
    { "CALL", CALL }, 
    { "CHECK", CHECK }, 
    { "CLASS", CLASS }, 
    { "CLUBLOG_QSO_UPLOAD_DATE", CLUBLOG_QSO_UPLOAD_DATE }, 
    { "CLUBLOG_QSO_UPLOAD_STATUS", CLUBLOG_QSO_UPLOAD_STATUS }, 
    { "CNTY", CNTY }, 
    { "CNTY_ALT", CNTY_ALT }, 
    { "COMMENT", COMMENT }, 
    { "COMMENT_INTL", COMMENT_INTL }, 
    { "CONT", CONT }, 
    { "CONTACTED_OP", CONTACTED_OP }, 
    { "CONTEST_ID", CONTEST_ID }, 
    { "COUNTRY", COUNTRY }, 
    { "COUNTRY_INTL", COUNTRY_INTL }, 
    { "CQZ", CQZ }, 
    { "CREATED_TIMESTAMP", CREATED_TIMESTAMP }, 
    { "CREDIT_GRANTED", CREDIT_GRANTED }, 
    { "CREDIT_SUBMITTED", CREDIT_SUBMITTED }, 
    { "DARC_DOK", DARC_DOK }, 
    { "DCL_QSLRDATE", DCL_QSLRDATE }, 
    { "DCL_QSLSDATE", DCL_QSLSDATE }, 
    { "DCL_QSL_RCVD", DCL_QSL_RCVD }, 
    { "DCL_QSL_SENT", DCL_QSL_SENT }, 
    { "DISTANCE", DISTANCE }, 
    { "DXCC", DXCC }, 
    { "EMAIL", EMAIL }, 
    { "EQSL_AG", EQSL_AG }, 
    { "EQSL_QSLRDATE", EQSL_QSLRDATE }, 
    { "EQSL_QSLSDATE", EQSL_QSLSDATE }, 
    { "EQSL_QSL_RCVD", EQSL_QSL_RCVD }, 
    { "EQSL_QSL_SENT", EQSL_QSL_SENT }, 
    { "EQ_CALL", EQ_CALL }, 
    { "FISTS", FISTS }, 
    { "FISTS_CC", FISTS_CC }, 
    { "FORCE_INIT", FORCE_INIT }, 
    { "FREQ", FREQ }, 
    { "FREQ_RX", FREQ_RX }, 
    { "GRIDSQUARE", GRIDSQUARE }, 
    { "GRIDSQUARE_EXT", GRIDSQUARE_EXT }, 
    { "GUEST_OP", GUEST_OP }, 
    { "HAMLOGEU_QSO_UPLOAD_DATE", HAMLOGEU_QSO_UPLOAD_DATE }, 
    { "HAMLOGEU_QSO_UPLOAD_STATUS", HAMLOGEU_QSO_UPLOAD_STATUS }, 
    { "HAMQTH_QSO_UPLOAD_DATE", HAMQTH_QSO_UPLOAD_DATE }, 
    { "HAMQTH_QSO_UPLOAD_STATUS", HAMQTH_QSO_UPLOAD_STATUS }, 
    { "HRDLOG_QSO_UPLOAD_DATE", HRDLOG_QSO_UPLOAD_DATE }, 
    { "HRDLOG_QSO_UPLOAD_STATUS", HRDLOG_QSO_UPLOAD_STATUS }, 
    { "IOTA", IOTA }, 
    { "IOTA_ISLAND_ID", IOTA_ISLAND_ID }, 
    { "ITUZ", ITUZ }, 
    { "K_INDEX", K_INDEX }, 
    { "LAT", LAT }, 
    { "LON", LON }, 
    { "LOTW_QSLRDATE", LOTW_QSLRDATE }, 
    { "LOTW_QSLSDATE", LOTW_QSLSDATE }, 
    { "LOTW_QSL_RCVD", LOTW_QSL_RCVD }, 
    { "LOTW_QSL_SENT", LOTW_QSL_SENT }, 
    { "MAX_BURSTS", MAX_BURSTS }, 
    { "MODE", MODE }, 
    { "MORSE_KEY_INFO", MORSE_KEY_INFO }, 
    { "MORSE_KEY_TYPE", MORSE_KEY_TYPE }, 
    { "MS_SHOWER", MS_SHOWER }, 
    { "MY_ALTITUDE", MY_ALTITUDE }, 
    { "MY_ANTENNA", MY_ANTENNA }, 
    { "MY_ANTENNA_INTL", MY_ANTENNA_INTL }, 
    { "MY_ARRL_SECT", MY_ARRL_SECT }, 
    { "MY_CITY", MY_CITY }, 
    { "MY_CITY_INTL", MY_CITY_INTL }, 
    { "MY_CNTY", MY_CNTY }, 
    { "MY_CNTY_ALT", MY_CNTY_ALT }, 
    { "MY_COUNTRY", MY_COUNTRY }, 
    { "MY_COUNTRY_INTL", MY_COUNTRY_INTL }, 
    { "MY_CQ_ZONE", MY_CQ_ZONE }, 
    { "MY_DARC_DOK", MY_DARC_DOK }, 
    { "MY_DXCC", MY_DXCC }, 
    { "MY_FISTS", MY_FISTS }, 
    { "MY_GRIDSQUARE", MY_GRIDSQUARE }, 
    { "MY_GRIDSQUARE_EXT", MY_GRIDSQUARE_EXT }, 
    { "MY_IOTA", MY_IOTA }, 
    { "MY_IOTA_ISLAND_ID", MY_IOTA_ISLAND_ID }, 
    { "MY_ITU_ZONE", MY_ITU_ZONE }, 
    { "MY_LAT", MY_LAT }, 
    { "MY_LON", MY_LON }, 
    { "MY_MORSE_KEY_INFO", MY_MORSE_KEY_INFO }, 
    { "MY_MORSE_KEY_TYPE", MY_MORSE_KEY_TYPE }, 
    { "MY_NAME", MY_NAME }, 
    { "MY_NAME_INTL", MY_NAME_INTL }, 
    { "MY_POSTAL_CODE", MY_POSTAL_CODE }, 
    { "MY_POSTAL_CODE_INTL", MY_POSTAL_CODE_INTL }, 
    { "MY_POTA_REF", MY_POTA_REF }, 
    { "MY_RIG", MY_RIG }, 
    { "MY_RIG_INTL", MY_RIG_INTL }, 
    { "MY_SIG", MY_SIG }, 
    { "MY_SIG_INFO", MY_SIG_INFO }, 
    { "MY_SIG_INFO_INTL", MY_SIG_INFO_INTL }, 
    { "MY_SIG_INTL", MY_SIG_INTL }, 
    { "MY_SOTA_REF", MY_SOTA_REF }, 
    { "MY_STATE", MY_STATE }, 
    { "MY_STREET", MY_STREET }, 
    { "MY_STREET_INTL", MY_STREET_INTL }, 
    { "MY_USACA_COUNTIES", MY_USACA_COUNTIES }, 
    { "MY_VUCC_GRIDS", MY_VUCC_GRIDS }, 
    { "MY_WWFF_REF", MY_WWFF_REF }, 
    { "NAME", NAME }, 
    { "NAME_INTL", NAME_INTL }, 
    { "NOTES", NOTES }, 
    { "NOTES_INTL", NOTES_INTL }, 
    { "NR_BURSTS", NR_BURSTS }, 
    { "NR_PINGS", NR_PINGS }, 
    { "OPERATOR", OPERATOR }, 
    { "OWNER_CALLSIGN", OWNER_CALLSIGN }, 
    { "PFX", PFX }, 
    { "POTA_REF", POTA_REF }, 
    { "PRECEDENCE", PRECEDENCE }, 
    { "PROGRAMID", PROGRAMID }, 
    { "PROGRAMVERSION", PROGRAMVERSION }, 
    { "PROP_MODE", PROP_MODE }, 
    { "PUBLIC_KEY", PUBLIC_KEY }, 
    { "QRZCOM_QSO_DOWNLOAD_DATE", QRZCOM_QSO_DOWNLOAD_DATE }, 
    { "QRZCOM_QSO_DOWNLOAD_STATUS", QRZCOM_QSO_DOWNLOAD_STATUS }, 
    { "QRZCOM_QSO_UPLOAD_DATE", QRZCOM_QSO_UPLOAD_DATE }, 
    { "QRZCOM_QSO_UPLOAD_STATUS", QRZCOM_QSO_UPLOAD_STATUS }, 
    { "QSLMSG", QSLMSG }, 
    { "QSLMSG_INTL", QSLMSG_INTL }, 
    { "QSLMSG_RCVD", QSLMSG_RCVD }, 
    { "QSLRDATE", QSLRDATE }, 
    { "QSLSDATE", QSLSDATE }, 
    { "QSL_RCVD", QSL_RCVD }, 
    { "QSL_RCVD_VIA", QSL_RCVD_VIA }, 
    { "QSL_SENT", QSL_SENT }, 
    { "QSL_SENT_VIA", QSL_SENT_VIA }, 
    { "QSL_VIA", QSL_VIA }, 
    { "QSO_COMPLETE", QSO_COMPLETE }, 
    { "QSO_DATE", QSO_DATE }, 
    { "QSO_DATE_OFF", QSO_DATE_OFF }, 
    { "QSO_RANDOM", QSO_RANDOM }, 
    { "QTH", QTH }, 
    { "QTH_INTL", QTH_INTL }, 
    { "REGION", REGION }, 
    { "RIG", RIG }, 
    { "RIG_INTL", RIG_INTL }, 
    { "RST_RCVD", RST_RCVD }, 
    { "RST_SENT", RST_SENT }, 
    { "RX_PWR", RX_PWR }, 
    { "SAT_MODE", SAT_MODE }, 
    { "SAT_NAME", SAT_NAME }, 
    { "SFI", SFI }, 
    { "SIG", SIG }, 
    { "SIG_INFO", SIG_INFO }, 
    { "SIG_INFO_INTL", SIG_INFO_INTL }, 
    { "SIG_INTL", SIG_INTL }, 
    { "SILENT_KEY", SILENT_KEY }, 
    { "SKCC", SKCC }, 
    { "SOTA_REF", SOTA_REF }, 
    { "SRX", SRX }, 
    { "SRX_STRING", SRX_STRING }, 
    { "STATE", STATE }, 
    { "STATION_CALLSIGN", STATION_CALLSIGN }, 
    { "STX", STX }, 
    { "STX_STRING", STX_STRING }, 
    { "SUBMODE", SUBMODE }, 
    { "SWL", SWL }, 
    { "TEN_TEN", TEN_TEN }, 
    { "TIME_OFF", TIME_OFF }, 
    { "TIME_ON", TIME_ON }, 
    { "TX_PWR", TX_PWR }, 
    { "UKSMG", UKSMG }, 
    { "USACA_COUNTIES", USACA_COUNTIES }, 
    { "USERDEFn", USERDEFn }, 
    { "VE_PROV", VE_PROV }, 
    { "VUCC_GRIDS", VUCC_GRIDS }, 
    { "WEB", WEB }, 
    { "WWFF_REF", WWFF_REF }, 

	{"", FIELD_MAX}
	};

	//! ADIF version string
	static char* VERSION = "3.1.6";

}
