#[=[
	Copyright 2026, Philip Rose, GM3ZZA
	
    This file is part of ZZALOG. Amateur Radio Logging Software.

    ZZALOG is free software: you can redistribute it and/or modify it under the
	terms of the Lesser GNU General Public License as published by the Free Software
	Foundation, either version 3 of the License, or (at your option) any later version.

    ZZALOG is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
	PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along with ZZALOG. 
	If not, see <https://www.gnu.org/licenses/>. 

#]=]

## CMake helper functions for vcpkg integration.
## This file was mostly generated by Claude Sonnet from prompts to assist with vcpkg integration, and is not intended to be a general-purpose vcpkg helper. 
## It is designed to work with the specific structure of this project.

# Copy vcpkg runtime DLLs to the install directory, 
# so that the installed application can find them at runtime.
function (install_vcpkg_dlls)
    # Install vcpkg runtime DLLs (boost, curl, zlib)
    set(VCPKG_INSTALL_BIN_DIR "")
    set(VCPKG_INSTALL_DEBUG_BIN_DIR "")

    if(_VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
      set(VCPKG_INSTALL_BIN_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin")
      set(VCPKG_INSTALL_DEBUG_BIN_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/bin")
    elseif(ZLIB_ROOT)
      set(VCPKG_INSTALL_BIN_DIR "${ZLIB_ROOT}/bin")
      set(VCPKG_INSTALL_DEBUG_BIN_DIR "${ZLIB_ROOT}/debug/bin")
    elseif(VCPKG_ROOT)
      if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(VCPKG_INSTALL_BIN_DIR "${VCPKG_ROOT}/installed/x64-windows/bin")
        set(VCPKG_INSTALL_DEBUG_BIN_DIR "${VCPKG_ROOT}/installed/x64-windows/debug/bin")
      else()
        set(VCPKG_INSTALL_BIN_DIR "${VCPKG_ROOT}/installed/x86-windows/bin")
        set(VCPKG_INSTALL_DEBUG_BIN_DIR "${VCPKG_ROOT}/installed/x86-windows/debug/bin")
      endif()
    endif()

    # Collect all runtime DLLs from both release and debug directories
    set(ALL_VCPKG_RUNTIME_DLLS "")

    if(VCPKG_INSTALL_BIN_DIR AND EXISTS "${VCPKG_INSTALL_BIN_DIR}")
      file(GLOB RELEASE_RUNTIME_DLLS 
        "${VCPKG_INSTALL_BIN_DIR}/boost_filesystem*.dll"
        "${VCPKG_INSTALL_BIN_DIR}/libcurl*.dll"
        "${VCPKG_INSTALL_BIN_DIR}/zlib*.dll"
      )
      list(APPEND ALL_VCPKG_RUNTIME_DLLS ${RELEASE_RUNTIME_DLLS})
    endif()

    if(VCPKG_INSTALL_DEBUG_BIN_DIR AND EXISTS "${VCPKG_INSTALL_DEBUG_BIN_DIR}")
      file(GLOB DEBUG_RUNTIME_DLLS 
        "${VCPKG_INSTALL_DEBUG_BIN_DIR}/boost_filesystem*.dll"
        "${VCPKG_INSTALL_DEBUG_BIN_DIR}/libcurl*.dll"
        "${VCPKG_INSTALL_DEBUG_BIN_DIR}/zlib*.dll"
      )
      list(APPEND ALL_VCPKG_RUNTIME_DLLS ${DEBUG_RUNTIME_DLLS})
    endif()

    if(ALL_VCPKG_RUNTIME_DLLS)
      install(FILES ${ALL_VCPKG_RUNTIME_DLLS}
        DESTINATION bin
        COMPONENT applications
      )
      message(STATUS "Will install vcpkg DLLs: ${ALL_VCPKG_RUNTIME_DLLS}")
    endif()
endfunction()